### ISSUE TITLE
OneSwitch Pulse plugin not always holding/resetting timer when user input is held

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#105]
I'm having issues with the One Switch Pulse utility, whereby the timer's (pulse + time-out) sometimes are ignoring that I might be holding a button down.

[https://www.dropbox.com/s/zoqchpp6pjsznbo/One%20Switch%20Pulse%20-%20Timer%20Reset%20inconsistent.mp4?dl=0](url)

You can see this (hopefully) in the rough video above. I'm holding down button 1 (A) and yet it's still at times pulsing button 2 down through the list in JoyToKey.

**Comment by oneswitch** [comment]
This should help with replicating the Pulsing problem where a held button is ignored....

1. Set CHOICE as button 1 AND PULSE as button 2 on your joypad. Additionally, set a button to button plugin so you can use button 1 as vjoy button 1, and button 2 as vjoy button 2 (for manual control/over-ride).


2. If you press button 1 only things work perfectly.
If you press button 2 on its own things work perfectly.

If you hold button 1 then tap button 2, it goes wrong (you can see it start to pulse even though you still have button 1 held).

3. Additionally, Pulse timers don't seem to pay any attention to physical axis motion. That would be very useful to do too, as it's possible we'll get someone who uses a single chin controller joystick and can manage just one extra button input. Pulsing would work out for them too, as well as pure one-switch users.

**Comment by evilC** [comment]
Thanks for isolating this one for me, Barrie - I see the problem now. I think what happened is that when writing the code to detect if any buttons were held, I treated any release event as meaning no more buttons were held.
