### ISSUE TITLE
OneSwitch Pulse: Button constantly on option 

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#106]
Request for an option to hold a button down constantly if One Switch Pulse is active.

- On/Off tick box for it being enabled or not.
- Ability to choose the vJoy button.

[This video shows the principle](https://www.dropbox.com/s/ptz3xk3rbu08ucl/One%20Switch%20Pulse%20-%20Held%20Button%20%2832%29%20Idea.mp4?dl=0)

If a fixed vJoy button (e.g. 32) could be held on whilst OneSwitch Pulse is active, it would enable that to be customised to do other things (e.g. accelerate / reverse / hand-brake to park) whilst the one-switch user could just worry about steering left/right or doing nothing and waiting for other options to be made available (via Pulsing or Time-Out).

**Comment by evilC** [comment]
Reqs understood.  

Add CheckBox GuiControl, and standard OutputButton control to Pulse. If checkbox is checked, the OutputButton is sent a down event on pulse starting, and an up event on pulse stopping.
