### ISSUE TITLE
Smoothing / Filtering of Mouse to Joystick Plugin Needed to avoid juddering effect

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#107]
The Mouse to Joystick plugin: is very jittery with an HMC Mini Joystick in Absolute mode. 

[https://www.dropbox.com/s/ll17tupus4jepw0/Mouse%20to%20Joy%20issues.mp4?dl=0](https://www.dropbox.com/s/ll17tupus4jepw0/Mouse%20to%20Joy%20issues.mp4?dl=0)

You did send me a fix for a much older version, but I think it needs to be as a GUI option if possible so it can be carried across and tweaked easily. Would be fantastic to get this working for a guy in Ireland I'm supporting through SpecialEffect.

**Comment by oneswitch** [comment]
This seems to be the version that fixed things (I need to grab an HMC Mini Joystick to be sure): [https://www.dropbox.com/sh/aec7gemhrimzv37/AAB1fx4bmUL4t35jIQnkjew_a?dl=0](url)

**Comment by evilC** [comment]
Try editing `Threads\ProfileInputThread.ahk`,  [line 32](https://github.com/evilC/UCR/blob/master/Threads/ProfileInputThread.ahk#L32)
`this.MouseTimeOutDuration := 10	; ToDo: Allow changing`
Try raising this value, it's in ms. It controls how long after it last saw the mouse move to wait before centering the axis.

**Comment by oneswitch** [comment]
Nice. :) That fixes it. Be great to have a way to tweak that value from the GUI.

The default that works great on the HMC Mini Joystick is

editing line 32 to              this.MouseTimeOutDuration := 160	; ToDo: Allow changing

Threshold 10 + Timeout 10 and Scale Factor 150.

I'm not quite sure what the Threshold and Timeout do, but it seems to work very nicely. Thank you.

**Comment by oneswitch** [comment]
Sorry! Next thing I've spotted as needed is a "Mouse axis to buttons plugin", to really open up these controllers. That would be fantastic.

**Comment by oneswitch** [comment]
Also, I'm not sure if "Scale Factor" actually does anything at the minute.

**Comment by evilC** [comment]
Scale Factor does work BTW, and is generally best when used in the range 0...1
ie decimals such as 0.5 can be used to make it less sensitive
