### ISSUE TITLE
OneSwitch Pulse: Intermittent failure to pass through the choice button

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#111]
With UCR OneSwitch Pulse plugin next to a button to button plugin, I'm finding that there is an intermittent failure to pass through the choice button to vJoy.

For instance, if I have OneSwitch Pulse set for "stick 2, button 1" to act as choice (as "vJoy 1 button 21"), and also to pass through as button to button ("vJoy 1 button 21", sometimes it seems to jam and not pass through anything to vJoy for button 21. 

If I delete the OneSwitch Pulse plugin and restart UCR,  the button to button plugin starts to work correctly. 

Hope you can fix this one, you normally can. :)

**Comment by oneswitch** [comment]
Just to reiterate....

**Comment by oneswitch** [comment]
Just to try to make clearer....

**Comment by oneswitch** [comment]
Just to make clearer hopefully...

Plugin: OneSwitch Pulse
 Choice = stick 2 - button 1

Plugin: Button to Button
 Remap Stick 2, Button 1 >>> Virtual Stick 1, Button 21

The problem is that button 21 will intermittently just completely jam and do nothing.

**Comment by evilC** [comment]
Was due to a limitation of UCR not being communicated to the user properly.
Bug #112 raised in response to this issue.
