### ISSUE TITLE
Add OneSwitch Pulse "TAB" key as an option for the pulse.

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#118]
Enabling the TAB key to be the pulsed output would enable very easy access for some switch users to the likes of this:

[http://www.bbc.co.uk/cbeebies/games/abneyandteal-fourinarow](url)

and would do away with JoyToKey.

**Comment by evilC** [comment]
Not getting why you cannot already. For the "Pulse Button" option, drop
down the list -> Select New Keyboard / Mouse -> Hit Tab

**Comment by oneswitch** [comment]
Ignore me, I'm clearly on drugs. You can do this perfectly. Sorry!
