### ISSUE TITLE
UCR not repositioning to take into account restarting on lower res / less screen space / single monitor

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#125]
That's a long way of saying that I can't see UCR, after placing it on a 2nd screen, shutting down, then restarting my laptop without the 2nd screen attached.

Solution is to reconnect the 2nd screen, or open UCR.ini and change what was....

"CurrentPos": {
  "x": 1958,
  "y": 43

to something on-screen, eg. "x": 50

**Comment by evilC** [comment]
This is a duplicate of #72 
BTW, you do not need to plug the 2nd monitor back in.
Just edit the ini file and set x and y to 0
