### ISSUE TITLE
Ultimarc Ultra-stik does not appear as a physical joystick.

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#130]
An Ultimarc Ultra-stik in joystick mode (it can be set to act as a mouse or a joystick HID), does not appear in the axis to axis plugin in UCR. Thus it can't be used directly.

It does appear as a standard joystick in the Windows game controller properties test utility, and does appear in JoyID Swapper.

**Comment by evilC** [comment]
Has it ever worked with any of my software?
Do the buttons work?

**Comment by oneswitch** [comment]
Just tested and the buttons are great, but the axis-to-axis is not picking
it up....

It only has a single axis set-up. Not sure if this is affecting anything.

[image: Inline images 1]

**Comment by evilC** [comment]
That's two axes FYI - x and y

We may have issues with the Ultimarc - AFAIK it uses a driver called vJoy, which is not the same as Shaul's vJoy. Didn't you say something about sending me one to test? We may need to.

**Comment by oneswitch** [comment]
Okay. I'll get some on order and will post one over for you to test with.
