### ISSUE TITLE
v0.1.1 issues

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#132]
Few error messages when starting up. Ignored, and it still started up.

Adding an axis to axis plugin, I'm getting "UCR.ahk" - "Error. A SubMenu with the name vJoy already exists in this menu". But I wasn't trying to add anything called vJoy, just "Y". This is a consistent error.

I don't think vJoy has correctly installed though.

"A vJoy install was found in C:\Program Files\vJoy\, but the relevant registry entries were not found.
Please update vJoy to the latest version from 

http://vjoystick.sourceforge.net."

But I did install from here: https://sourceforge.net/projects/vjoystick/files/Beta%202.x/
!

**Comment by evilC** [comment]
Fixed
