### ISSUE TITLE
Axis Splitter plugin not functioning correctly with Xbox Triggers (Z-axis)

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#136]
Problem:

Xbox 360 joypad connected, testing with LT and RT (Z-axis).
Trying to output to Titan One or vJoy using Axis Splitter plugin.
Getting very strange response, as if the Playstation/Xbox button was being pressed. And if not that, I'm getting no response whatsoever (as seems to be the case presently)...

E.g.

Input Axis: Stick 3, Axis 3      Output Axes Titan One Axis 5 (Low)     Titan One Axis 6 (High).

This is also the case for the "Axis to Axis" plugin.

**Comment by oneswitch** [comment]
It's working correctly now, although would benefit from invert/deadzone/sensitivity/linear options

**Comment by evilC** [comment]
OK, will close and create new ticket
