### ISSUE TITLE
L2/LT and R2/RT Titan One output not correct when triggered by buttons.

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#138]
Using the button to button plugin, I'm getting no response on a PS4 with the triggers.

For instance, I may have 

Input: key "2"    mapped to Titan One Button 7 ("PS3 L2 / PS4 L2")
Input: key "9"    mapped to Titan One Button 8 ("PS3 R2 / PS4 R2")

There's no response on the Playstation (using a driving game). However, if I set the Titan One to Xbox 360 output, B6 and B7 (on http://html5gamepad.com/) are getting very weedy output (0.01) when I press 2 or 9.

Looks like a simple decimal place error, perhaps. But also, I wonder why XBOX LT/RT is not appearing on that list of output choices.

Not sure if this problem follows across to vJoy output too.

**Comment by oneswitch** [comment]
A little more investigation. 

With the Titan One set to PS4 mode, the button to button plugin for L2/R2 produces these results in HTML5 Gamepad Tester by holding down both associated keys to trigger L2/R2....

B6 = 1.00
B7 = 1.00
AXIS3 drops from -1 to -0.984314
AXIS4 drops from -1 to -0.984314

A standard PS4 controller when attached responds in a similar way, but the axis is different...

B6 and b7 go to 1.00.
There's only Axis 0-3 appearing and do not react to me pressing 2 and 9.

The Titan is kicking out more axis (0-9) but this may be linked to passing gyroscope info etc. through USB, and the standard PS4 controller sending it part by USB and part by blue-tooth.

Bit of a head-scratcher.

**Comment by oneswitch** [comment]
But it was working a long time ago.

**Comment by oneswitch** [comment]
Various issues it seems. I'm unable to get clean correct output from the"Button to Axis" plugin, nor the Button to Button" axis when mapping across to Titan One R2/RTrigger and L2/LTrigger output.

**Comment by evilC** [comment]
Fixed
