### ISSUE TITLE
changing case of entry name doesnt work

### ISSUE THREAD

**Issue by My1** [evilC/UCR#171]
it tells you that the name already exists and you have to change to something else first.

**Comment by evilC** [comment]
Entry name?  
I take it you mean if you rename a profile or plugin?

**Comment by My1** [comment]
the name of a binding, i guess you mean plugin, didnt try profiles yet

**Comment by evilC** [comment]
Fixed.  
Save this profile.ahk over your old one (In Classes folder)  
https://raw.githubusercontent.com/evilC/UCR/b72edd51a62ab0ac32d382a21c050c7c4ed95ab8/Classes/Profile.ahk

**Comment by evilC** [comment]
It seems that renaming profiles is also broken.  
I raised issue #172 for this.

**Comment by evilC** [comment]
ah, hang on.  
I changed some code in this regard, so the version of Profile.ahk that I linked will probably be incompatible with your version.  
Lemme fix the profile renaming bug and I will give you a link to download the new version.

**Comment by evilC** [comment]
UCR 0.1.12 has been released, which should address these issues.  
To upgrade, just copy your UCR.ini to the new folder.
