### ISSUE TITLE
I may be really stupid, but there is no UCR.exe in the Folder...

### ISSUE THREAD

**Issue by Alias-Me** [evilC/UCR#175]
I can`t find a .exe to run like in the readme.txt

**Comment by evilC** [comment]
If you pulled from the GitHub repo, you will not get a UCR.exe  
UCR.exe is only present in the release ZIPs  
UCR.exe is actually AutoHotkey.exe from AHK_H, renamed. It is NOT a compiled version of UCR.

**Comment by Alias-Me** [comment]
Oh ok thx!

**Comment by alakious** [comment]
Hi
Thanks for UCR great app. But I had a little problem with my controller. My controller's button  cannot be blocked so I can't change it to a true Xbox controller.
Actually I wanna change my "1" key to "Y" key in Xbox controller or change my "4" key to "1"key of my controller.
Please update.Really thnx

**Comment by evilC** [comment]
If your game is detecting your physical controller and you do not want it to, then this cannot currently be stopped. There is a new project coming which will potentially fix this, but not yet.  
For now, one workaround to try is to  
1) Start UCR and make sure it has created the virtual XBox controller.  
2) UNPLUG your real controller.  
3) Start the game  
4) Plug in your real controller.  

In this way, hopefully the game only cares about the fake xbox controller that was plugged in when you started the game.

**Comment by alakious** [comment]
I hope this project finishes as soon as possible.
Really thnx for both ucr and ur next project but if u could add blocking option for joystick buttons & joystick output in an update that's enough for me and for MORTAL KOMBAT X
