### ISSUE TITLE
Axis to Joystick (missing physical Joystick Axis selection)

### ISSUE THREAD

**Issue by s1ww** [evilC/UCR#183]
(Axes To Mouse) goes flawessly

but

(Mouse Axis To Joystick Axis) -> there is only vJoy selection that is useless for me (vJoy has faulty values in some apps)

physical Joysticks Axes are missing! we cant output mouse signal to stick directly! ;(

please update UCR ASAP  :x

**Comment by evilC** [comment]
Not a bug.
It is not technically possible to output to a physical joystick.
