### ISSUE TITLE
Profile Switching Problems

### ISSUE THREAD

**Issue by starfuryth** [evilC/UCR#186]
Having an issue with the profile switcher function, specifically switching between a standard profile and a "shifted" profile on button press/release (not a toggle).

If I press and release the programmed "shift" button slowly, the profile switcher switches properly between two child profiles - call it profile B (shifted) on button press, and profile A (default) on release. But if I tap the button quickly, the UCR will only switch to the opposite profile (from B to A, or from A to B) and doesn't switch back until I tap the button again.

Is there a way to resolve this issue?

**Comment by evilC** [comment]
I will see if I can reproduce and let you know.

**Comment by starfuryth** [comment]
Update: This is a non-issue, and I apologize for posting without doing adequate troubleshooting on my end.

Initially, the only way I could get the profile switching to work was to add profile switchers to both child profiles as well as the parent. Turns out one of the child profiles didn't have the "Profile inherits plugins from parent" box checked.  Checked this box for both profiles, removed the extraneous child profile switcher plugins, and all is good!

Thank you, and sorry again.
