### ISSUE TITLE
Support for more than 8 controllers

### ISSUE THREAD

**Issue by supersmo** [evilC/UCR#188]
It would be great if more than 8 controllers could be used in UCR on the input side of the plugins.

I have a case where I need to merge 8 gamepads into 4 gamepads to be detected by a game.
As it is now it is a bit tricky to do since both physical and virtual gamepads show up on the input side of the plugins so in this case there would be 12 gamepads but only the first 8 show up in the list.

**Comment by evilC** [comment]
This is never going to be supported in this version of UCR, as UCR uses AutoHotkey's joystick support, which is limited to 8 devices (Plus each device only supports 32 buttons, 6 axes, 1 POV).  
The next version of UCR will support the full DirectInput range (?Unlimited? joysticks, 128 buttons, 8 axes, 4 POVs per stick)

**Comment by supersmo** [comment]
OK
Thanks for the explanation.
