### ISSUE TITLE
Profile Switcher doesn't work perfectly on Joystick button release.

### ISSUE THREAD

**Issue by Secmess** [evilC/UCR#189]
Basically, I tried to do a multi-state joystick. I think it's called "Shift State" around here. Unfortunately it doesn't work pretty well, since the Profile Switcher on the new profile won't detect the release of previously pressed joystick button.

I have to press and release the specified button again on the new profile to be able to trigger the current Profile Switcher.

Currently:
[Profile 1] press X -> [Profile 2] release X -> [Still Profile 2] press then release X -> Profile 1
Should be:
[Profile 1] press X -> [Profile 2] release X -> [Profile 1]

Though using keyboard input, that plugin works pretty good.

**Comment by Secmess** [comment]
Welp, sorry. It actually works as well as using keyboard bindings now (thought there's a noticeable amount of time between press-release for the profile to detect it). I didn't know what caused the problem before.

**Comment by Secmess** [comment]
Welp, tested again and somehow doesn't work anymore on two out of two different occasions.

**Comment by Secmess** [comment]
Okay, decided to read the "designed" Shift State scheme and found out that you ought to use Profile Inheritance. Finally worked flawlessly.

Setup:
[Parent] Profile Switcher - go to B in X press and A in Y press
  [A] Something
  [B] Something

Lol, things totally make sense now. Using parent, the profile switcher will be active every time; even during changing states.

**Comment by evilC** [comment]
Ahh, that's what it was, I could not figure out what your problem was.  
Glad you finally sorted it out.
