### ISSUE TITLE
UCR T1 no access to gyros

### ISSUE THREAD

**Issue by oneswitch** [evilC/UCR#195]
Would be great if there was some way to replicate this T1 script...

        if(get_val(PS3_LY) > 20) {set_val(PS3_ACCY, get_val(PS3_LY)/4); set_val(PS3_LY, 0);} 
          else {set_val(PS3_ACCY, get_val(PS3_LY)/4); set_val(PS3_LY, 0);}

        if(get_val(PS3_LX) > 20) {set_val(PS4_ACCZ, -25);set_val(PS4_ACCX, get_val(PS3_LX)/4 * -1);set_val(PS4_GYROY, get_val(PS3_LX)/15 * -1);set_val(PS3_LX, 0);} 
          else {set_val(PS4_ACCZ, -25); set_val(PS4_ACCX, get_val(PS3_LX)/4 * -1); set_val(PS4_GYROY, get_val(PS3_LX)/15 * -1); set_val(PS3_LX, 0);}

This kind of flexibility enables better six-axis access. This would enable control over Everybody's Gone to the Rapture's six-axis areas for a start.

**Comment by evilC** [comment]
Implemented
