### ISSUE TITLE
Not saving. (solved)

### ISSUE THREAD

**Issue by DonParpan** [evilC/UCR#201]
I tried to use UCR for some time now. While it does kinda work it doesn't save anything I've mapped. I have the newest version so that shouldn't be the problem.

**Comment by evilC** [comment]
Does it not write anything to UCR.ini? Is the file maybe read-only or something?

**Comment by DonParpan** [comment]
I asume that would be in the Folder where the exe is? Because neither is there such a file in that folder nor in a subfolder.

**Comment by evilC** [comment]
What are the permissions on the folder? Maybe it cannot create the file.

**Comment by DonParpan** [comment]
It should have permission. I currently have it on my desktop in a new made folder. also tried it on another drive already. same result.

**Comment by evilC** [comment]
Try creating an AHK file in the same folder with this content and run it:  

`FileAppend, test, xyz.ini`  

Does `xyz.ini` get created in the folder?

**Comment by DonParpan** [comment]
...I seem to have general write permission right now. Some programs can, some can't. It works in a folder I kinda got to work for other stuff.
Nothing wrong with your software, just my computer being fucked up. I'm going to try to fix that somehow. Thanks for helping.
