### ISSUE TITLE
two keyboards identification

### ISSUE THREAD

**Issue by Eran111** [evilC/UCR#204]
Hey there..!
i've read this post about 2 mice recognition:
https://github.com/evilC/UCR/issues/184

i got to it after looking entirely in the internet for an option of playing local co-ops with two keyboards and two mouse.
with UCR its actually possible!
how?
my "theory" is by configuring a second keyboard to pretend to be a controller, and a mouse pretending to be the wheel joystick - UCR could provide couch co-op! (such as portal :))

problem is that now connecting two mouse/two keyboards - seems that UCR cant differ between two input keyboards. so while binding a key on one keyboard, the second responds to the same key.

remaining problem will be ignoring the "controller keyboard" to interfere with "windows keyboard" keys. but it might be solvable if configuring  2 controllers maybe.

what do you think about that? you think its possible to make UCR recognize and differ between multiple keyboards?
Thanks!
Eran

**Comment by evilC** [comment]
Only if you use different keys on each keyboard.  
I am currently re-writing UCR in C#, and the new version supports per-device bindings, so this would be possible in the new version.  
We are hoping to release an initial alpha sometime soon, keep an eye on the UCR thread on the AHK forums, I will announce it there.

**Comment by Eran111** [comment]
Awsome!
if it will be per-device bindings, wouldn't it be possible to configure two different controllers with two keyboards using the same keys?
that way the different keys on each keyboard might be solvable

**Comment by Eran111** [comment]
sound sweet.
then i think it will be possible to intercept the "controller keyboard" in order to send it only to UCR while leave the main keyboard out of the loop. am i right?
(if so, ure gonna do a great favor to all local co-op gamers..! :) )

**Comment by evilC** [comment]
Yup  
The initial version will probably not feature blocking, but it is technically feasible with interception.

**Comment by Eran111** [comment]
hey hey!
i've been looking for new release updates for the ucr.. is it already possible (not like before) to bind two different Keyboards without interrupting to each other? 
thanks :)

**Comment by evilC** [comment]
This version of UCR is not being developed any more, and that feature will never make it in.  
The new [UCR-C#](https://github.com/Snoothy/UCR) has this feature.  
If you want to do this in AHK, you can use my [AutoHotInterception](https://autohotkey.com/boards/viewtopic.php?f=6&t=45307) library.
