### ISSUE TITLE
Not being recognized by games?

### ISSUE THREAD

**Issue by poyui** [evilC/UCR#205]
Trying to use it together with vJoy, it shows in the  vJoy monitor that it is working the keybiddings that i used but both in Cuphead and Atelier Sophie it isn't working.

**Comment by evilC** [comment]
Are the games expecting xbox controllers? If so, are you using xXBox or vJoy?

**Comment by poyui** [comment]
Atelier is expecting a xbox controller but it doesn`t have a configuration panel to see if it can add others, but Cuphead can and it doesn`t show any controller being installed. Using vJoy

**Comment by poyui** [comment]
For what is worth the problem seems to be with autohotkey as i tried using a simple script just with the accept button on the keyboard for both games and neither did work on the game but worked outside. Don't know if you can do much at this point.

**Comment by evilC** [comment]
Run UCR as admin. Cuphead cannot accept input from non-elevated processes.  
Or use the new [UCR-C#](https://github.com/Snoothy/UCR) as this sends input at a driver level.
