### ISSUE TITLE
Current capabilities for unity co-op.

### ISSUE THREAD

**Issue by rjb25** [evilC/UCR#207]
Hello!

Hopefully this is an easy close. I am simply wondering which of the following are currently possible given the state of this repo. If they are not currently possible when if ever might they be?

1. Converting separate mice axis to separate joystick axis. (Check! Got this working. I can move two different mice and it affects two different characters looking direction.)
2. Separate mice clicks/mousewheel to separate joystick trigger actions.
3. Remapping a given keyboards WASD to arrow keys. This would allow both players to use WASD and in unity it would be able to tell which players movement was desired. WASD versus arrow keys in this case.

Thanks!

**Comment by evilC** [comment]
This feature has just been added to version 0.4.0 of the new [UCR-C#](https://github.com/Snoothy/UCR). It will never be possible in this version (UCR-AHK) due to the way it processes keyboard / mouse input.
