### ISSUE TITLE
The profile could not be activated

### ISSUE THREAD

**Issue by Salvobioinfo** [evilC/UCR#222]
I tried to configure thrustmaster Hotas X with xbox controller, but after i have done the profile when I want to activate it didn't go, I get thise errore message: the profile could not be activated, see the log for more details ... another thing is that how to save created profile? The save button is not active 
I don't know where to find log file.

**Comment by Salvobioinfo** [comment]
Sorry for empty question, my pc is crazy, im´not able to edit and adjust the question. 
I tried to configure thrustmaster Hotas X with xbox controller, but after i have done the profile when I want to activate it didn't go, I get thise errore message: the profile could not be activated, see the log for more details ... 
I don't know where to find log file.

**Comment by evilC** [comment]
This sounds like a bug for [UCR-C#](https://github.com/Snoothy/UCR), not UCR-AHK
