### ISSUE TITLE
Feature Request: KB to vJoy axis.

### ISSUE THREAD

**Issue by Osjur** [evilC/UCR#60]
Can you add a plugin where one could map keyboard binds to Vjoy axis. Button to Button plugin doesn't have that feature. 

Reason for that would be to bind WASD to +X- & +Y- axis on the stick. This would be for movement for ex.

axis would also need to recenter after you have stopped pressing the button

**Comment by evilC** [comment]
Oh yeah, this is most certainly going to be added, it is just a matter of time.

**Comment by evilC** [comment]
This has been implemented in Alpha 0.0.2, which I just released.
FYI, currently you cannot bind arrow keys in UCR. This is a known bug (#62) and will be looked into.
WASD works fine though.
