### ISSUE TITLE
Typing things into a "Banner Combo" box can cause crash

### ISSUE THREAD

**Issue by shauleiz** [evilC/UCR#68]
I think the following pic is self explanatory:
![image](https://cloud.githubusercontent.com/assets/13401124/12072279/a846026a-b0df-11e5-9d86-d2cfb881c26c.png)

**Comment by Osjur** [comment]
Yeah was going to report this one as well. After you have made the bind, the cursor still stays / blinks at the box and it writes your key presses to that box.

Like in that pic for example.

**Comment by evilC** [comment]
Am not able to repro this, works fine for me.
In that pic, how did you interact with the Y dropdown? did you drop it down and select a stick or an axis? ie at what point did it break?

**Comment by shauleiz** [comment]
I just typed '1' into the combo box

**Comment by evilC** [comment]
Oh, it was just that?
I am not going to investigate this one for now, for the simple reason that you should not be able to type anything into these boxes. The fact that you can is only because I cannot work out yet how to disable just the EditBox component of a ComboBox.
Reworking these ComboBoxes is something I plan on looking into as they already cause problems with the mouse wheel (If one has focus and you roll the mouse wheel, it changes selection - this is why we had to change the parent of the combobox, resulting in you sometimes seeing the editbox portion of the combobox appear in a different place)
So yeah, a bunch of work needs doing in that area, but it is not a top priority.

**Comment by evilC** [comment]
Osjur wrote:
Configure any plugin you want with default profile, in my case, ButtonToButton, and set the keybinds. After you have set up the keybinds, click on the main program window and the cursor starts blinking at the last dropbox where you set your keybind. Now if you press the keybind you have remapped, it writes that data to the last dropbox and crashes the program.
![cursor blinks](https://cloud.githubusercontent.com/assets/9019921/12078153/103469f8-b210-11e5-816d-cc1e7ab57e84.png)
Same answer to this as above.

**Comment by evilC** [comment]
Osjur wrote:
Set up MouseToJoy plugin, Set up ButtonToAxis, no need to even map anything. Close the program and restart it. You can see your cursor blinking at X AXIS Threshold. Do it the other way around and you can see your cursor blinking at ButtonToAxis upper input dropbox.

**Comment by evilC** [comment]
Osjur wrote:
Set up ButtonToButton, remap A to 1. Add MouseToJoy, no need to set up any mappings but you can do it and this still happens. Close the program and start it again. Click MouseToJoy dropbox and you will see cursor blinking there. Press A and it will either write junks there or crash the program.
![junk](https://cloud.githubusercontent.com/assets/9019921/12078238/6fc5529a-b212-11e5-9c87-850bd07f0431.png)

**Comment by evilC** [comment]
OK, I pulled all the bits from Osjurs post in #64 that I think are all basically the same issue.

With that said, and bearing in mind my comments above, knowing that there are issues in this area, are you able to work around it for now or do I need to elevate the priority on this?

**Comment by shauleiz** [comment]
EvilC - so I think you want a List box rather than a Combo box - take a look at this:
https://support.office.com/en-ca/article/Create-a-list-of-choices-by-using-a-list-box-or-combo-box-70abf4a9-0439-4885-9099-b9fa83517603

**Comment by evilC** [comment]
AFAIK listboxes do not support a "Cue Banner".
The Cue Banner is used to display the current binding or a prompt (eg "Drop down the list to select a binding..") but this item *should not* appear in the list when you drop it down.

**Comment by evilC** [comment]
BannerCombo replaced with BannerMenu in 0.0.17
BannerMenu is not susceptible to this issue.
