### ISSUE TITLE
Multiple axis merge output to wrong vJoy Axis

### ISSUE THREAD

**Issue by DOCaCola** [evilC/UCR#78]
Great work on UCR!
I have tried to adapt my profile from UJR to UCR and noticed an issue.
I have defined two merge axis plugins. The first combines a throttle control and the second one combines the X-axis from two joysticks.
Therefore the first merge plugin outputs to the throttle axis (S1) and the second merge plugin to the X-Axis. However the second merge plugin which should output to the x-axis also controls the throttle control.
Both merge plugins (and the axis to axis plugin) output to vJoy device 2.

[UCR.ini.txt](https://github.com/evilC/UCR/files/158317/UCR.ini.txt)

![axiserror](https://cloud.githubusercontent.com/assets/2077396/13521453/e748b91e-e1e8-11e5-90b5-69fc4320276d.png)

**Comment by evilC** [comment]
I can see why this is happening.

I will release a new version this weekend, but until then you could fix it by editing Plugins\Core|AxisMerge.ahk and:

change ```static OutAxis := 0``` to ```this.OutAxis := 0```
Then replace the 3 other instances of ```OutAxis``` in that file with ```this.OutAxis```

**Comment by evilC** [comment]
Actually, correction.
Just replace your ```AxisMerge.ahk``` with this one:
https://raw.githubusercontent.com/evilC/UCR/child-profiles/Plugins/Core/AxisMerge.ahk

**Comment by DOCaCola** [comment]
Yes. This seems to have fixed the issue. Thanks
